name: hds_learn_jupyter
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=2.2.6
  - matplotlib=3.2.1
  - numpy=1.18.1
  - nodejs=10.13.0
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
